apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # this defines which pods are represented by service
  # this will become n/w endpoint for other services or external users (browser etc)
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30000

  type: NodePort
